sudo: required
services:
    - docker

before_install:
    - docker build -t luongnv1810/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true luongnv1810/frontend npm run test -- --coverage
env:
    - YARN_GPG=no
      